# ======================================
# APPLICATION MACSPACE - CONFIGURATION
# ======================================
spring.profiles.active=dev
# ======================================
# JWT CONFIGURATION
# ======================================
application.security.jwt.secret-key=wzUpGa9k4LTV3QHuY8qVrt6wOENkvdes5vLHVc1ex6581IiQ
application.security.jwt.expiration=36000000
# ======================================
# BASE DE DONNÉES
# ======================================
spring.datasource.url=jdbc:mysql://localhost:3306/macspace?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=macspace_user
spring.datasource.password=MacSpace2024!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ======================================
# JPA / HIBERNATE
# ======================================
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# ======================================
# INTERCEPTEUR MULTI-TENANT
# ======================================
spring.jpa.properties.hibernate.session_factory.statement_inspector=com.macspace.gestiondestock.interceptor.MacSpaceInterceptor
# ======================================
# SERVEUR
# ======================================
server.port=8080
server.error.include-message=on_param
server.error.include-stacktrace=never
# ======================================
# LOGGING
# ======================================
logging.level.root=INFO
logging.level.com.macspace=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
# ======================================
# SPRINGDOC / SWAGGER
# ======================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
# ======================================
# FLICKR
# ======================================
flickr.apiKey=b1def0cbab8494d153378d5a6acdcb2e
flickr.apiSecret=e1bbdc2d2e6ac1d6
flickr.appKey=72157720925355594-ece0693e87f634c3
flickr.appSecret=f29cb93685d98704